server:
  port: 8085

spring:
  application:
    name: demo-account1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/study_hmily_dubbo?useUnicode=true&characterEncoding=utf8&transformedBitIsBoolean=true&autoReconnect=true&serverTimezone=Asia/Shanghai&useCursorFetch=true
    username:  root
    password:  123456
dubbo:
  scan:
    base-packages: com.jjh.transaction
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost